config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :achievements, only: [:new, :create, :index, :destroy]
  resources :posts
  resources :post_achievements, only: [:create]
  resources :categories, only: [:new, :create, :index]
  resources :votes, only: [:create]
  resources :users, only: [:show, :index, :destroy] do
    member do
      get 'toggle_rights'
    end
  end
  resources :comments, only: [:create]

  namespace :api do
    resources :visits, only: %i(create) # => [:create]
    resources :statistics, only: %i(show)
  end

  resources :statistics, only: %i(index show) do
    member do
      get 'post'
    end
  end

  resources :callouts

  root 'categories#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :achievements, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :nullify
  has_many :comments, dependent: :destroy
  has_many :visits, dependent: :destroy

  def voted_for?(ach, post)
    post_achievement = PostAchievement.find_by(post: post, achievement: ach)
    votes.any? {|v| v.post_achievement == post_achievement }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :require_admin!, except: [:show]

  def show
    @user = User.find_by(id: params[:id])
  end

  def index
    @users = User.order('created_at DESC').page(params[:page])
  end

  def destroy
    @user = User.find_by(id: params[:id])
    unless @user == current_user
      flash[:success] = "User deleted..."
    end
    redirect_to users_path
  end

  def toggle_rights
    respond_to do |format|
      @user = User.find_by(id: params[:id])
      @user.toggle!(:admin) if @user
      format.js
    end
  end
end

app/views/users/_user.html.erb
<li id="user-<%= user.id %>">
  <%= gravatar_for user %>
  <%= user.name %>
  (<%= user.email %>)
  <% if user.admin? %>
    <span class="label label-info admin">admin</span>
  <% end %>
  <%= link_to 'Toggle rights', toggle_rights_user_path(user), class: 'btn btn-info',
              remote: true %>
  <%= link_to 'Delete', user_path(user),
              method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
</li>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <%= render @users %>
</ul>

<%= paginate @users %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div class="row">
  <div class="col-sm-3">
    <%= gravatar_for @user, size: 150, class: 'img-rounded' %>
    <p class="text-muted">Joined at <%= @user.created_at.strftime('%d %B %Y') %></p>
    <% if @user == current_user %>
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-info' %>
    <% end %>
  </div>

  <div class="col-sm-9">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#created" role="tab">Created achievements</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#received" role="tab">Received achievements</a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active fade in active" id="created" role="tabpanel">
        <h3>Created achievements</h3>

        <ul>
          <%= render @user.achievements %>
        </ul>
      </div>

      <div class="tab-pane active fade" id="received" role="tabpanel">
        <h3>Received achievements</h3>

        <% @user.posts.each do |post| %>
          <% post.achievements.each do |ach| %>
            <%= render(ach) if ach.assigned_for?(post) %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/toggle_rights.js.erb
var user = $('#user-<%= @user.id %>');
<% if @user.admin? %>
user.find('.btn.btn-info').before('<span class="label label-info admin">admin</span>&nbsp;');
<% else %>
user.find('.admin').fadeOut();
<% end %>