config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :achievements, only: [:new, :create, :index, :destroy]
  resources :posts
  resources :post_achievements, only: [:create]
  resources :categories, only: [:new, :create, :index]
  resources :votes, only: [:create]
  resources :users, only: [:show, :index, :destroy] do
    member do
      get 'toggle_rights'
    end
  end
  resources :comments, only: [:create]

  namespace :api do
    resources :visits, only: %i(create) # => [:create]
    resources :statistics, only: %i(show)
  end

  resources :statistics, only: %i(index show) do
    member do
      get 'post'
    end
  end

  resources :callouts

  root 'categories#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true # TODO: remove it
  has_many :post_achievements
  has_many :achievements, through: :post_achievements
  has_many :comments
  has_many :visits, dependent: :destroy

  #scope :received_achievements, achievements

  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :require_admin!, only: [:destroy, :edit, :update]

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:success] = "Post destroyed!"
    redirect_to posts_path
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = 'Post edited!'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def create
    p = post_params
    @category = Category.find_by(id: p.delete('category_id'))
    @post = current_user.posts.build(p)
    if @category
      @post.category = @category
      if @post.save
        flash[:success] = 'Post created!'
        redirect_to posts_path
      else
        render 'new'
      end
    else
      flash.now[:warning] = 'Category does not exist...'
      render 'new'
    end
  end

  def index
    @category = Category.includes(:posts, :callouts).find_by id: params[:category]
    if @category.present?
      @posts = @category.posts
      @callouts = @category.callouts
    else
      @posts = Post.all
    end
    @posts = @posts.order('created_at DESC').page(params[:page])
  end

  def show
    @post = Post.includes(:achievements, :comments).find_by(id: params[:id])
    @callouts = @post.category.callouts.order(Arel.sql('random()')).limit(3)
    @comment = Comment.new
    @ach_to_assign = (Achievement.where(community: true) + (current_user.nil? ? [] : current_user.achievements) - @post.achievements).uniq
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/views/posts/_callout.html.erb
<div>
  <%= link_to image_tag(callout.image.url), callout.url, target: '_blank' %>
  <p><%= callout.description %></p>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= render 'shared/errors', object: @post %>

  <fieldset class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <%= f.text_field :title, autofocus: true, class: "form-control", required: true %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :body, class: 'control-label' %>
    <%= f.text_area :body, class: "form-control", required: true %>
  </fieldset>

  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.all, :id, :title %>

  <%= f.submit 'Submit!', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= post.title %></h4>
    <h6 class="card-subtitle text-muted">
      <% if post.category %>
        <span class="label label-pill label-info"><%= post.category.title %></span>
      <% end %>
      <%= post.user.name %>
    </h6>
    <p class="card-text"><%= truncate sanitize(post.body, tags: []), length: 200 %></p>

    <%= link_to 'Read more', post_path(post), class: 'btn btn-primary' %>

    <% if current_user && current_user.admin? %>
      <%= link_to edit_post_path(post), class: 'btn btn-info' do %>
        Edit
      <% end %>

      <%= link_to post_path(post), method: :delete,
                                 data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' do %>
        <i class="icon-bin"></i>
        Delete
      <% end %>
    <% end %>

    <div class="card-footer text-muted">
      <%= time_ago_in_words post.created_at %> ago
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= header("Edit #{@post.title}") %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= header('Posts')%>


<%= link_to 'New Post', new_post_path, class: 'btn btn-primary btn-lg' %>


<% if @category.present? %>
  <div class="d-none track-visits" data-category="<%= @category.id %>"></div>
<% end %>

<div class="row">
  <div class="col-md-9">
    <%= render @posts %>
  </div>

  <div class="col-md-3">
    <div class="card">
      <div class="card-block">
        <h2>Related products</h2>
        <%= render partial: 'callout', collection: @callouts, as: :callout %>
      </div>
    </div>
  </div>
</div>


<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="d-none track-visits" data-post="<%= @post.id %>"></div>

<div class="row">
  <div class="col-md-9">
    <div class="post">
      <div class="card">
        <div class="card-block">
          <p class="text-muted"><i class="icon-clock"></i> <%= @post.timestamp %></p>

          <p><%= gravatar_for @post.user, size: 60, class: 'avatar' %>
            <em><%= link_to @post.user.name, user_path(@post.user) %></em></p>
        </div>

        <div class="card-block">
          <%= sanitize @post.body, tags: %w(iframe a img) %>
        </div>
      </div>
    </div>

    <h3><i class="icon-trophy"></i> Achievements</h3>

    <% @post.achievements.each do |ach| %>
      <div class="card">
        <div class="card-block row">
          <div class="col-md-2">
            <%= image_tag ach.image.thumb('100x100#').url, alt: ach.title %>
          </div>

          <div class="col-md-7">
            <h4 class="card-title"><%= ach.title %></h4>

            <p class="card-text">
              <%= ach.description %>
            </p>
          </div>

          <div class="col-md-3">
            <% if ach.assigned_for?(@post) %>
              <i class="icon-checkmark text-success text-bigger"></i>
            <% else %>
              <span class="label label-info">Votes: <%= ach.votes_for(@post) %></span>
              <% if current_user %>
                <% if current_user.voted_for?(ach, @post) %>
                  <span class="label label-danger">You have already voted!</span>
                <% elsif ach.user == current_user %>
                  <span class="label label-info">You've assigned this!</span>
                <% else %>
                  <%= form_tag votes_path do %>
                    <%= hidden_field_tag 'achievement_id', ach.id %>
                    <%= hidden_field_tag 'post_id', @post.id %>
                    <%= button_to nil, class: 'btn btn-info btn-sm' do %>
                      <i class="icon-arrow-up"></i>
                      Vote!
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>

            <p class="card-text text-muted">
              Assigned by <%= link_to ach.user.name, user_path(ach.user) %>
            </p>
          </div>
        </div>
      </div>
    <% end %>

    <% unless !current_user || @post.user == current_user %>
      <%= form_tag post_achievements_path, method: :post do %>
        <%= hidden_field_tag 'post_id', @post.id %>
        <fieldset class="form-group">
          <%= label_tag "achievements", 'Select achievement', class: 'control-label'%>
          <%= select_tag "achievement_id",
                         options_from_collection_for_select(@ach_to_assign, 'id', 'title'),
                         class: "form-control" %>
        </fieldset>

        <%= submit_tag 'Assign!', class: 'btn btn-primary btn-xs' %>
      <% end %>
    <% end %>

    <hr>

    <h3><i class="icon-bubbles"></i> Comments</h3>

    <% if current_user %>
      <%= form_for @comment, remote: true do |f| %>
        <%= hidden_field_tag 'post_id', @post.id %>

        <fieldset class="form-group">
          <%= f.label :body, 'Your comment' %>
          <%= f.text_area :body, class: 'form-control' %>
        </fieldset>

        <%= f.submit 'Comment!', class: 'btn btn-primary' %>
      <% end %>
    <% end %>

    <div id="comments-list">
      <%= render @post.comments.order('created_at DESC') %>
    </div>
  </div>

  <div class="col-md-3">
    <div class="card">
      <div class="card-block">
        <h2>Related products</h2>
        <%= render partial: 'callout', collection: @callouts, as: :callout %>
      </div>
    </div>
  </div>
</div>