config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :achievements, only: [:new, :create, :index, :destroy]
  resources :posts
  resources :post_achievements, only: [:create]
  resources :categories, only: [:new, :create, :index]
  resources :votes, only: [:create]
  resources :users, only: [:show, :index, :destroy] do
    member do
      get 'toggle_rights'
    end
  end
  resources :comments, only: [:create]

  namespace :api do
    resources :visits, only: %i(create) # => [:create]
    resources :statistics, only: %i(show)
  end

  resources :statistics, only: %i(index show) do
    member do
      get 'post'
    end
  end

  resources :callouts

  root 'categories#index'
end

app/models/callout.rb
class Callout < ApplicationRecord
  has_many :category_callouts
  has_many :categories, through: :category_callouts

  dragonfly_accessor :image

  validates :url, presence: true

  validates_property :width, of: :image, as: 200 # , in: (0..400)
  validates_property :height, of: :image, as: 200
  # jpg, bmp, png
  # other validations: https://markevans.github.io/dragonfly/models#validations
end

app/controllers/callouts_controller.rb
class CalloutsController < ApplicationController
  def index
    @callouts = Callout.order('created_at DESC')
  end

  def edit
    @callout = Callout.find_by id: params[:id]
  end

  def update
    @callout = Callout.find_by id: params[:id]
    if @callout.update callout_params
      flash[:success] = 'Callout updated!'
      redirect_to callouts_path
    else
      render :edit
    end
  end

  def new
    @callout = Callout.new
  end

  def create
    @callout = Callout.new callout_params
    if @callout.save
      flash[:success] = 'Callout added!'
      redirect_to callouts_path
    else
      render :new
    end
  end

  private

  def callout_params
    params.require(:callout).permit(:url, :description, :image, :category_ids)
  end
end

app/views/callouts/_callout.html.erb
<li>
  <%= link_to 'Edit', edit_callout_path(callout) %><br>
  URL: <%= callout.url %><br>
  Description: <%= callout.description %><br>

  <ul>
    Categories: <% callout.categories.each do  |cat| %>
      <li>
        <%= cat.title %>
      </li>
    <% end %>
  </ul>

  <%= image_tag callout.image.url %>
</li>

app/views/callouts/_form.html.erb
<%= form_for callout do |f| %>
  <%= render 'shared/errors', object: callout %>

  <%= f.text_field :url, placeholder: 'URL' %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.collection_select :category_ids, Category.all, :id, :title %>

  <%= f.file_field :image %>

  <%= f.submit %>
<% end %>

app/views/callouts/edit.html.erb
<h1>Edit callout</h1>

<%= render 'form', callout: @callout %>

app/views/callouts/index.html.erb
<h1>Callouts</h1>

<%= link_to 'Add callout', new_callout_path, class: 'btn btn-lg btn-primary' %>

<ul>
  <%= render @callouts %>
</ul>

app/views/callouts/new.html.erb
<h1>New callout</h1>

<%= render 'form', callout: @callout %>