config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :achievements, only: [:new, :create, :index, :destroy]
  resources :posts
  resources :post_achievements, only: [:create]
  resources :categories, only: [:new, :create, :index]
  resources :votes, only: [:create]
  resources :users, only: [:show, :index, :destroy] do
    member do
      get 'toggle_rights'
    end
  end
  resources :comments, only: [:create]

  namespace :api do
    resources :visits, only: %i(create) # => [:create]
    resources :statistics, only: %i(show)
  end

  resources :statistics, only: %i(index show) do
    member do
      get 'post'
    end
  end

  resources :callouts

  root 'categories#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Achievements</title>
  <%= csrf_meta_tags %>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
</head>

<body>

<nav class="navbar navbar-expand navbar-dark bg-dark">
  <%= link_to 'LifeChieve', root_path, class: 'navbar-brand' %>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to 'Achievements', achievements_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'New category', new_category_path, class: 'nav-link' %>
    </li>
  </ul>

  <ul class="navbar-nav justify-content-end">
    <% if user_signed_in? %>
      <% if current_user && current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= gravatar_for current_user %>
      </li>
      <li class="nav-item">
        <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</nav>

<main role="main" class="container-fluid">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</main>

</body>
</html>